### ISSUE TITLE
Can leafmap crop an area based on lat and lon ranges?

### ISSUE THREAD

**Issue by GongdaLu** [giswqs/leafmap#108]
### Description
Dear Professor Wu

I noticed that some Python packages (e.g. Plotly and Bokeh) can draw maps, normally based on the coordinates of a given center point. Then the user can zoom in and out. But when somebody needs to crop the exact domain based on the given ranges of lat and lon, zooming manually is not ideal. 

I wonder if you have interest/time to add a feature in leafmap so that the user can input ranges of lat and lon, then save out the map as png or other common formats. 

I understand that this may be unnecessary for other users at all.  But I would like to share this idea with you. I will also think about how to achieve this using Python.

Many thanks,
Gongda

### Source code

```
Paste your source code here if have sample code to share.
```

**Comment by giswqs** [comment]
Yes, this would be a nice feature to add. A similar request has been submitted before. See https://github.com/giswqs/leafmap/issues/36.

I have not had time to implement this yet. Contributions are welcome!

**Comment by giswqs** [comment]
Leafmap already has four plotting backends, including ipyleaflet, folium, heremap, and kepler.gl. I thought about adding plotly as a new plotting backend, but I have not had time to implement it yet.

**Comment by sackh** [comment]
@giswqs - Please assign this issue to me, I will try to implement plotly backend.

**Comment by giswqs** [comment]
@sackh That would be awesome! I have opened a new issue for adding plotly. See https://github.com/giswqs/leafmap/issues/109

**Comment by giswqs** [comment]
@GongdaLu Sorry for taking so long. This feature has now been implemented. See the notebook example
https://github.com/giswqs/leafmap/blob/master/examples/notebooks/51_clip_image.ipynb
