### ISSUE TITLE
Specify optional requirements for rasters

### ISSUE THREAD

**Issue by cipri-tom** [giswqs/leafmap#11]
### Description

If we want to work with rasters, an error is thrown that `xarray_leaflet` is not installed.
We can list this as an optional dependency, via [`extras_require`](https://stackoverflow.com/a/10572833/786559) parameter to `setup()`. So the users who need raster support, would issue `pip install leafmap[raster]`.

What do you think ? This has the downside of specifying the dependency in `setup.py` rather than `requirements.txt`.

Alternatively, we can leave it as is (instructing users to install), but then we should fix the error display in the map:

![Screenshot 2021-05-31 at 15 26 25](https://user-images.githubusercontent.com/2991890/120200600-cf738e00-c224-11eb-9673-3f95139dc3e2.png)

The final error message is not visible.
Can we make that zone scrollable ?

**Comment by giswqs** [comment]
Thanks for the suggestion. I have improved the code. The output widgets is now scrollable. 

![Peek 2021-05-31 14-10](https://user-images.githubusercontent.com/5016453/120229010-422b3c00-c21a-11eb-93d7-a31be604b833.gif)

**Comment by cipri-tom** [comment]
Super fast ! Thanks !
