### ISSUE TITLE
style_callback param for add_geojson() not working?

### ISSUE THREAD

**Issue by deeplook** [giswqs/leafmap#119]
### Environment Information

-   leafmap version: 0.5.0
-   Python version: 3.9
-   Operating System: Linux/macOS

### Description

I want to use the `style_callback` parameter for `map.add_geojson()`, but the chosen style which sets only the color seems not to be respected. I think the style dicts are the same for ipyleaflet and leafmap, at least I could not find any contradictory information. See below.

```python
import requests
data = requests.get((
    "https://raw.githubusercontent.com/telegeography/www.submarinecablemap.com"
    "/master/web/public/api/v3/cable/cable-geo.json"
)).json()
callback = lambda feat: {"color": feat["properties"]["color"]}
```

```python
import leafmap
m = leafmap.Map(center=[0, 0], zoom=2)
m.add_geojson(data, style_callback=callback)
m.layout.height = "100px"
m
```

<img width="704" alt="Screen Shot 2021-10-03 at 11 12 53" src="https://user-images.githubusercontent.com/1001778/135747358-09d121b3-bcbc-44ff-992b-ee9036255963.png">

```python
import ipyleaflet
m = ipyleaflet.Map(center=[0, 0], zoom=2)
m += ipyleaflet.GeoJSON(data=data, style_callback=callback)
m.layout.height = "100px"
m
```

<img width="705" alt="Screen Shot 2021-10-03 at 11 14 14" src="https://user-images.githubusercontent.com/1001778/135747399-52943e61-da18-4365-96e7-76cc1e55dac6.png">

**Comment by giswqs** [comment]
Thanks for reporting. This bug has been fixed. It was caused by the default `style` argument that overwrites the `style_callback` argument. 

``` python
import leafmap
m = leafmap.Map(center=[0, 0], zoom=2, height="400px")
in_geojson = 'https://raw.githubusercontent.com/telegeography/www.submarinecablemap.com/master/web/public/api/v3/cable/cable-geo.json'
callback = lambda feat: {"color": feat["properties"]["color"]}
m.add_geojson(in_geojson, layer_name="Cable lines", style_callback=callback)
m
```
![image](https://user-images.githubusercontent.com/5016453/135756044-aba6f9cd-ddca-4df0-8afa-b4d558e096b1.png)

**Comment by deeplook** [comment]
Thank you!! BTW, I see the same issue with geemap 0.9.2, where it seems to work for `fillColor`, but not `color`. Shall I open a ticket there, too?

**Comment by giswqs** [comment]
Yes, please. Thanks.

**Comment by deeplook** [comment]
I've tested this in 0.6.0 with `m.add_gdf()` now which seems to behave like `m.add_geojson()` used to, showig only black cables for this snippet. Is there a relationship to https://github.com/jupyter-widgets/ipyleaflet/issues/785 where `style_callback` is not yet supported for geo dataframes?

```python
import random
import leafmap
import geopandas as gpd

m = leafmap.Map(center=[20, 0], zoom=1)
gdf = gpd.read_file('https://raw.githubusercontent.com/giswqs/leafmap/master/examples/data/cable-geo.geojson')
m.add_gdf(gdf, 
    style_callback=lambda feat: {"color": random.choice(["red", "green", "black"])}
)
m
```

**Comment by giswqs** [comment]
The function has a `fill_colors` parameter for setting random filled colors. It works for polygons but not polylines. I will look into it.

```python
import random
import leafmap
import geopandas as gpd

m = leafmap.Map(center=[20, 0], zoom=1)
gdf = gpd.read_file('https://raw.githubusercontent.com/giswqs/leafmap/master/examples/data/countries.geojson')
m.add_gdf(gdf, 
    fill_colors = ["red", "green", "black"])
m
```

**Comment by deeplook** [comment]
Thanks! I'm using the random colors only to keep the snippet short, but I'm more interested in a general callback that has access to the individual geo dataframe rows like the GeoJSON variant can access single features.

**Comment by giswqs** [comment]
@deeplook This bug has been fixed. Please update the package and have a try. 

![image](https://user-images.githubusercontent.com/5016453/145751308-cfabedfb-8bfb-46e1-a22c-1b0d63be04e7.png)

**Comment by deeplook** [comment]
Awesome, thanks! In the meantime I've found an easy workaround, at least in cases like this:

```python
import random
import leafmap
import geopandas as gpd

m = leafmap.Map(center=[20, 0], zoom=1)
gdf = gpd.read_file('https://raw.githubusercontent.com/giswqs/leafmap/master/examples/data/cable-geo.geojson')
m.add_geojson(gdf.geometry.__geo_interface__,  # convert to GeoJSON!
    style_callback=lambda feat: {"color": random.choice(["red", "green", "black"])}
)
m
```

**Comment by pakrajausama** [comment]
Aslam Alikm 

Version: 0.37.5
leafmap 
------------
I am unable to use this style_callback function;

code:

import leafmap
import geopandas as gpd


shapefile_path = 'mydata/New_Shapefile.shp'


gdf = gpd.read_file(shapefile_path)


m = leafmap.Map(center=[30, 70], zoom=6)  


m.add_gdf(gdf,
          style_callback=lambda feat: {"color": "blue" if feat['properties']['type'] == 'Type_a' else "orange", "fillOpacity": 0.6}
)
m

**Comment by giswqs** [comment]
@pakrajausama This bug has been fixed in https://github.com/opengeos/leafmap/pull/898. Please upgrade your leafmap to the latest version.

**Comment by pakrajausama** [comment]
Thank you very much; it's working perfectly now. I sincerely appreciate your guidance, Teacher @giswqs. Sending my respect and best wishes from Pakistan.
