### ISSUE TITLE
Add GUI for downloading OpenStreetMap  data

### ISSUE THREAD

**Issue by giswqs** [giswqs/leafmap#12]
Download OSM data without coding.

**Comment by AliyyaTirangga** [comment]
Please add GUI for downloading OpenStreetMap historical data in easy steps. I have found a reference about downloading OpenStreetmap historical data [here](https://gis.stackexchange.com/questions/167690/downloading-historical-openstreetmap-data) but I can't follow that tutorial. Probably it can be available in existing GUI for downloading OpenStreetMap data.

**Comment by giswqs** [comment]
@AliyyaTirangga Sorry, downloading OpenStreetMap historical data won't be supported in leafmap as there is no API for retrieving historical data for a specific area. Downloading a huge file at the country or global scale is not useful. You can go to https://planet.openstreetmap.org to manually download the data.
