### ISSUE TITLE
Support netcdf file

### ISSUE THREAD

**Issue by zxdawn** [giswqs/leafmap#127]
### Description

As `geemap` has supported the netcdf file (https://github.com/giswqs/geemap/issues/285), it's better to add it to `leafmap` like https://github.com/davidbrochart/xarray_leaflet/issues/12.

### Source code

Anyway, I use `xarray_leaflet` temporarily:

```
import leafmap
import xarray as xr
import xarray_leaflet

m = leafmap.Map(center=(40, -100), zoom=4)

data = xr.open_dataset('../data/tropomi_regrid/monthly/S5P_OFFL_L2__NO2____qa50_qa75_csd_202001-202108.nc')['tropospheric_NO2_column_number_density'].isel(time=0)

l = data.leaflet.plot(m, x_dim='longitude', y_dim='latitude', colormap='vidiris')

m.add_tile_layer(l, name="TROPOMI NO2", attribution="Test")
```

Error:
```
Exception: The 'url' trait of a TileLayer instance expected a unicode string, not the LocalTileLayer LocalTileLayer(name='tropospheric_NO2_column_number_density', options=['attribution', 'detect_retina', 'max_native_zoom', 'max_zoom', 'min_native_zoom', 'min_zoom', 'no_wrap', 'tile_size', 'tms']).
```

Is it possible to add the `LocalTileLayer` to map?

**Comment by giswqs** [comment]
Use `m.add_layer()` rather than `m.add_tile_layer()` to add LocalTileLayer. See https://ipyleaflet.readthedocs.io/en/latest/api_reference/local_tile_layer.html

Adding netCDF support is on my to-do-list. I don't have a timeline to implement it yet. Contributions are welcome.

**Comment by giswqs** [comment]
@zxdawn Leafmap now supports NetCDF data. See notebook example https://leafmap.org/notebooks/52_netcdf/

**Comment by zxdawn** [comment]
@giswqs Thanks a lot for your hard work!
