### ISSUE TITLE
Add cesium to streamlit function

### ISSUE THREAD

**Issue by giswqs** [giswqs/leafmap#139]
The feature allows rendering a cesium html file in a streamlit web app

**Comment by giswqs** [comment]
This feature has been implemented. See https://streamlit.gishub.org

![image](https://user-images.githubusercontent.com/5016453/145748809-f489fbc9-719f-4568-a74b-5ce2cf2dfebd.png)

**Comment by williamhatch** [comment]
@giswqs thanks, I noticed that cesium_to_streamlit  is a static Streamlit Component, meaning, no information is passed back from Leaflet on browser interaction... can we have another FR to allow pass back interactive info to other component?

**Comment by giswqs** [comment]
Yes, you are welcome to submit a PR.
