### ISSUE TITLE
Add circle markers from xy

### ISSUE THREAD

**Issue by giswqs** [giswqs/leafmap#140]
References:

- https://python-visualization.github.io/folium/modules.html#folium.vector_layers.CircleMarker
- https://ipyleaflet.readthedocs.io/en/latest/api_reference/circle_marker.html

**Comment by giswqs** [comment]
This feature has been implemented. See notebook example https://leafmap.org/notebooks/35_circle_markers/

![](https://i.imgur.com/1KrVRL9.gif)

**Comment by EmanuelCastanho** [comment]
How can all the points be grouped into a single layer?

![Screenshot 2023-10-11 at 13 29 28](https://github.com/opengeos/leafmap/assets/69935277/d2461144-8634-43cc-b192-62d210253557)

**Comment by giswqs** [comment]
See https://leafmap.org/notebooks/35_circle_markers/

**Comment by EmanuelCastanho** [comment]
Dear @giswqs , I followed this tutorial, but there the circle markers are not included in the layer control panel.
Instead of a layer for each point is it possible to have a single layer for all points?
