### ISSUE TITLE
map_to_html output map missing layers

### ISSUE THREAD

**Issue by Niko-La** [giswqs/leafmap#141]
Built a map consist of area boundary lines using geojson, added csv markers and a heatmap layer.

Exporting on local build is not working using gui widget.

Running the hosted binder export html results in only the map showing the heat map, the other two layers are not showing.   Further more the right hand side panel is not present in the html map.

### Environment Information

-   leafmap version:
-   Python version:
-   Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by giswqs** [comment]
This is an ipyleaflet issue. Leafmap can't support this until ipyleaflet supports it. 

- https://github.com/jupyter-widgets/ipyleaflet/issues/810
- https://github.com/jupyter-widgets/ipyleaflet/issues/896
