### ISSUE TITLE
rendering heatmap always starts from zoomed out usa view

### ISSUE THREAD

**Issue by Niko-La** [giswqs/leafmap#142]
every heatmap render starts from the map of the usa zoomed out.  Is it possible to pass along the initial center coordinates and zoom level to the heatmap render?

### Environment Information

-   leafmap version:
-   Python version:
-   Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by giswqs** [comment]
You can specify the map center when creating the map. 

```python
import leafmap
m = leafmap.Map(center=[40, 10], zoom=5)
m.add_basemap("Stamen.Toner")
filepath = "https://raw.githubusercontent.com/giswqs/leafmap/master/examples/data/world_cities.csv"
m.add_heatmap(filepath, latitude="latitude", longitude='longitude', value="pop_max", name="Heat map", radius=20)
m
```

![image](https://user-images.githubusercontent.com/5016453/146110069-02db0269-93a9-441a-a9a1-2bd1b9d0475d.png)

**Comment by deeplook** [comment]
I've also thought many times it would be nice for a "global" user base of such a great package like this to start with a less US-centric view of the world. 😉

**Comment by giswqs** [comment]
@deeplook Good suggestion. It has been implemented. https://github.com/giswqs/leafmap/issues/143
