### ISSUE TITLE
CRSError: Invalid projection: epsg:4326 on OSM notebook example

### ISSUE THREAD

**Issue by Niko-La** [giswqs/leafmap#157]
`
CRSError: Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name)
`

### Environment Information
leafmap-0.6.1
Python 3.9.7
windows 10 pro

Could be related to this issue
https://github.com/geopandas/geopandas/issues/1887

![image](https://user-images.githubusercontent.com/14004559/147516070-9ff42682-65be-4c62-a75f-f59802e41955.png)

**Comment by giswqs** [comment]
This is likely a system specific issue. It works fine on my Linux machine and on GitHub. As suggested in https://github.com/geopandas/geopandas/issues/1887#issuecomment-805014414, you might need to install geopandas and pyproj from conda-forge. Under the hood, the leafmap `add_osm_from_geocode()` function simply wraps `ox.geocode_to_gdf()`. It is only one line of code. If there is an issue, that means it originates from geopandas or osmnx. There is not much I can do about this issue. 

https://github.com/giswqs/leafmap/blob/40973aed104376d04280d9215ce2d9e464681d3f/leafmap/osm.py#L309-L312


https://leafmap.org/notebooks/15_openstreetmap
![image](https://user-images.githubusercontent.com/5016453/147518024-7042f287-2052-4b0e-b033-a301331fca09.png)
