### ISSUE TITLE
Get pixel value by lat/lon from a local tile (COG)

### ISSUE THREAD

**Issue by giswqs** [giswqs/leafmap#162]
Thanks to localtileserver @banesullivan https://github.com/banesullivan/localtileserver/issues/43, it is now possible to get pixel values from a local tile. This feature will improve the Inspector tool to support local tile. 

https://github.com/banesullivan/localtileserver/blob/main/localtileserver/client.py#L183

```python
from localtileserver import get_leaflet_tile_layer, TileClient
from ipyleaflet import Map

# First, create a tile server from local raster file
tile_client = TileClient('~/Downloads/dem.tif')

# Create ipyleaflet tile layer from that server
t = get_leaflet_tile_layer(tile_client)

# Create ipyleaflet map, add tile layer, and display
m = Map(center=tile_client.center())
m.add_layer(t)
m

tile_client.pixel(37.869365, -118.943481, units="EPSG:4326")
```
![image](https://user-images.githubusercontent.com/5016453/147722462-78a49c06-ceed-4295-8663-b0eee787de87.png)

**Comment by giswqs** [comment]
This feature has been implemented. See notebook example https://github.com/giswqs/leafmap/blob/master/examples/notebooks/32_local_tile.ipynb

![](https://i.imgur.com/dy6LSq5.gif)

**Comment by banesullivan** [comment]
Available in localtileserver >=0.3.14

**Comment by banesullivan** [comment]
@giswqs, I really need to add some tests to this to verify I'm grabbing the right values... Need to find a sample raster with simple data/big pixels. I will look in the GDAL testing data

**Comment by giswqs** [comment]
I just did some testing, and there are indeed some issues with the pixel values. The same image, same lon/lon with different results with Titiler endpoint and localtileserver. 

```python
import leafmap
import localtileserver
m= leafmap.Map()
url = "https://s3.eu-central-1.amazonaws.com/floris.calkoen.open.data/tile_2523.tif"
m.add_cog_layer(url, bands=[4, 3, 2])
m
```

```python
remote_url = "https://s3.eu-central-1.amazonaws.com/floris.calkoen.open.data/tile_2523.tif"
local_url = "~/Downloads/landsat.tif"
lat = 53.404415
lon = 6.872292
leafmap.cog_pixel_value(lon, lat, url)
tile_client = localtileserver.TileClient(local_url)
leafmap.local_tile_pixel_value(lon, lat, tile_client)
```

![image](https://user-images.githubusercontent.com/5016453/147789660-36569a9c-716b-4245-9753-2fa9fd715e04.png)

**Comment by banesullivan** [comment]
The values aren't widely different which gives me some hope that this may be a precision issue with either large_image/localtileserver or titiler.

I will try to add some tests in localtileserver to make sure everything is good there.

**Comment by banesullivan** [comment]
I will add that this is extensively tested in large_image and localtileserver simply wraps this functionality. https://github.com/girder/large_image/blob/9251babd4acaa0eecd37c4749f7d9eeac6379171/test/test_source_gdal.py#L148

But I'd still like to add some sort of user/visual test in localtileserver
