### ISSUE TITLE
add_cog_mosaic fails - does new Titiler version support creating MosaicJSONs?

### ISSUE THREAD

**Issue by robintw** [giswqs/leafmap#180]
### Environment Information

-   leafmap version: 0.7.2
-   Python version: 3.9
-   Operating System: Windows

### Description
I am trying to add a mosaic of COGs to leafmap, using the following code:

```
m.add_cog_mosaic(["https://opendata.digitalglobe.com/events/california-fire-2020/post-event/2020-08-14/pine-gulch-fire20/10300100AAC8DD00.tif"])
```

(This is a simple mosaic for testing, with just a single image in it).

I get the following error:

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~\Documents\mambaforge\envs\anglo\lib\site-packages\leafmap\common.py in cog_mosaic(links, titiler_endpoint, username, layername, overwrite, verbose, **kwargs)
   1072         ).json()
-> 1073         token = r["token"]
   1074 

KeyError: 'token'

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_18396/3959939009.py in <module>
----> 1 m.add_cog_mosaic(["https://opendata.digitalglobe.com/events/california-fire-2020/post-event/2020-08-14/pine-gulch-fire20/10300100AAC8DD00.tif"])

~\Documents\mambaforge\envs\anglo\lib\site-packages\leafmap\leafmap.py in add_cog_mosaic(self, links, name, attribution, opacity, shown, titiler_endpoint, username, overwrite, show_footprints, verbose, **kwargs)
    803         """
    804         layername = name.replace(" ", "_")
--> 805         tile = cog_mosaic(
    806             links,
    807             titiler_endpoint=titiler_endpoint,

~\Documents\mambaforge\envs\anglo\lib\site-packages\leafmap\common.py in cog_mosaic(links, titiler_endpoint, username, layername, overwrite, verbose, **kwargs)
   1094 
   1095     except Exception as e:
-> 1096         raise Exception(e)
   1097 
   1098 

Exception: 'token'
```

I've done some investigating of this, and it seems that the titiler server running at http://titiler.xyz doesn't support the `/tokens/create` endpoint, or the `mosaicjson/create` endpoint - see the (automatically generated) docs page at http://titiler.xyz/docs.

From looking at some of the old PRs, it seemed this endpoint is the new version of the https://api.cogeo.xyz/ server - and that server _does_ have the relevant endpoints (see https://api.cogeo.xyz/docs).

I've also had a look at the titiler code, and I can't see anything about /tokens/create or /mosaicjson/create endpoints in the latest titiler version (0.4).

Does anyone know what is going on here? Was this an old feature of titiler that was removed? If so, does this functionality need removing from leafmap? Or is there a possibility to add this feature back into titiler (it would be useful for some other applications of titiler that I'm working on).

Pinging @vincentsarago as he probably knows about the titiler side of this.

**Comment by vincentsarago** [comment]
@robintw yeah we removed mosaic creation endpoint in `titiler.xyz` (which is a pure titiler master deployed). cogeo.xyz endpoint was a modified version of titiler, which will soon disappear. 

> Or is there a possibility to add this feature back into titiler (it would be useful for some other applications of titiler that I'm working on).

The problem with it, is that it requires storage (here we use dynamodb) which is a cost on devseed, it's just not safe at the moment to keep it without proper authentification method.

on your own endpoint you could easily add a mosaic creation endpoint: see https://github.com/developmentseed/titiler/blob/master/docs/advanced/customization.md#add-a-mosaicjson-creation-endpoint https://github.com/developmentseed/titiler/blob/master/docs/examples/code/tiler_with_auth.md

**Comment by giswqs** [comment]
@robintw Thanks for looking into this. It has been a while since I used the `add_cog_mosaic()` function, probably more than a year ago. As @vincentsarago pointed out, the mosaic creation endpoint is no longer supported by `titiler.xyz`. I will have to remove the mosaic function from leafmap.

**Comment by giswqs** [comment]
The `add_cog_mosaic()` function has been removed from leafmap. Will re-implement it in the future when it becomes possible.
