### ISSUE TITLE
Search Control

### ISSUE THREAD

**Issue by poissonk** [giswqs/leafmap#182]
As in ipyleaflet (https://ipyleaflet.readthedocs.io/en/latest/api_reference/search_control.html?highlight=search), is it possible to add a Search Control to search features from a GeoJSON layer in leafmap ?

Regards,

**Comment by giswqs** [comment]
Good suggestion. This would be a nice feature to add. Pull requests are welcome. I will implement it when I have time.

**Comment by giswqs** [comment]
This feature has been implemented. Update the package using `leafmap.update_package()` and restart the kernel to take effect. @poissonk @rowheat02 
https://github.com/giswqs/leafmap/blob/master/examples/notebooks/43_search_control.ipynb

![43_search_control](https://user-images.githubusercontent.com/5016453/150596975-e672c920-3f56-4626-a17c-e521c682fa71.gif)

**Comment by poissonk** [comment]
Awesome, thank you very much @giswqs
