### ISSUE TITLE
Draw: the circle shap save to point

### ISSUE THREAD

**Issue by ydfang** [giswqs/leafmap#184]
### Environment Information

-   leafmap version: The current leafmap version in GitHub version
-   Python version: 3.9
-   Operating System: Windows 10

### Description
When I draw a circle and a marker in the map, then I export them to data.geojson. 

I open the geojson file, and I found there are two points. (The circle shape was saved to a point)

### What I Did

```
import leafmap.foliumap as leafmap

width, height = 900, 800


def app():
    center = [34.6252978589571, -77.34580993652344]
    zoom = 10
    m = leafmap.Map(center=center, zoom=zoom, draw_export=True)

    m.to_streamlit(width=width, height=height)


app()
```

**Comment by giswqs** [comment]
This is something related to the folium package. There is nothing leafmap can do about that. I have opened an issue at 
https://github.com/python-visualization/folium/issues/1565

![folium](https://user-images.githubusercontent.com/5016453/150208974-f6bbbb2d-e282-456d-9da5-461e756f6745.gif)
