### ISSUE TITLE
Support fit_bounds=False in leafmap.add_raster

### ISSUE THREAD

**Issue by MikeBeller** [giswqs/leafmap#186]
Thank you for providing leafmap (and geemap).  It's really a remarkable tool.

Issue: When I add multiple geotiff rasters to a leafmap using `add_raster`, the map zooms around like crazy.  This is because `xarray_leaflet.plot()` has signature `plot(....., fit_bounds=False)` and `leafmap.add_raster` does not support a `fit_bounds` keyword argument.

The feature requested is simple:  Add `fit_bounds` to `leafmap.add_raster` signature, and pass it through to `xarray_leaflet.plot` in the same function.

I could create a PR to implement this if you wish.  It's a tiny amount of code. (I already hacked my own local copy of leafmap)  Please advise.

**Comment by giswqs** [comment]
Good suggestion. Please submit a PR so that you can get the credit. I would love to have more contributors to leafmap.

**Comment by giswqs** [comment]
Thanks for the PR. Will merge it shortly. 

You might also be interested in the `add_local_tile()` function based on [localtileserver](https://github.com/banesullivan/localtileserver),  which is a replacement of the `add_raster()` function based on xarray-leaflet. 

https://leafmap.org/notebooks/32_local_tile/
https://leafmap.org/notebooks/41_raster_gui/

https://user-images.githubusercontent.com/5016453/150684119-88bbcb57-da60-4976-a273-0b0f5f7b5827.mp4

https://user-images.githubusercontent.com/5016453/150684127-8bcaa227-5451-47ce-a037-594beee4dd36.mp4

**Comment by MikeBeller** [comment]
Thanks @giswqs I will check these out more thoroughly.  For your info: I popped the first one up in your binder and it looked like `add_local_tile` didn't seem to work in there.  Checking chrome devtools the tiles are getting blocked on 404 not found.  I think it might be because the binder notebook server starts before localtileserver is installed (the pip install is in the notebook which is after the single-user notebook server is started).  It might be necessary to add localtileserver is to the binder requirements.  Not sure.

**Comment by giswqs** [comment]
@MikeBeller You are correct. localtileserver does not work on binder yet, but it works locally. See https://github.com/banesullivan/localtileserver-demo/issues/1 @banesullivan

If you have COG stored in the cloud, you can also use `add_cog_layer()` or `add_remote_tile()`. See https://leafmap.org/notebooks/03_cog_stac/.
