### ISSUE TITLE
Can't add a Geotiff raster layer to the map

### ISSUE THREAD

**Issue by mamoev** [giswqs/leafmap#19]
### Environment Information

-   leafmap version: 0.1.0
-   Python version: 3.7.10
-   Operating System: Windows

### Description

After installing xarray-leaflet, I tried to add a Geotiff raster layer to the map.

Once the file is chosen, I press the apply button and the map zooms to the right coordinates, a layer is created but nothing is displayed.

I'm attaching the file I'm trying to display so you can try on your own.

[file.zip](https://github.com/giswqs/leafmap/files/6618022/file.zip)

**Comment by giswqs** [comment]
Are you using Windows? Unfortunately, xarray_leaflet does not work properly on Windows. See https://github.com/davidbrochart/xarray_leaflet/issues/30 @davidbrochart 

Alternatively, you can use Linux-based Binder. 

- https://gishub.org/leafmap-pangeo
- https://gishub.org/leafmap-binder

**Comment by davidbrochart** [comment]
Sorry, I still haven't got the time to work on xarray-leaflet :smile:

**Comment by mamoev** [comment]
Thanks for the quick responses.

I will test this on Linux.

**Comment by mamoev** [comment]
I tested the Binder links you provided and, in a Linux environment, it works great.

However, when running an example notebook (05_load_raster) locally, it doesn't work anymore. I have two loading icons in the bottom right corner that are displayed indefinitely. No layer is created

**Comment by giswqs** [comment]
@mamoev The binder env was created using this [environment.yml](https://github.com/giswqs/leafmap/blob/master/environment.yml). Can you try creating a fresh env using the same yml?

```
conda env create -f environment.yml
```

**Comment by mamoev** [comment]
Thanks for the help ! It works great.

**Comment by robinjacobroy** [comment]
I tried to load a raster image in Google Colab but, no layer is getting added. Only the map gets zoomed to the location of the raster. 
Same is the case in my local system. Please help..

**Comment by giswqs** [comment]
Xarray-leaflet does not support Colab. Try binder https://gishub.org/leafmap-pangeo
Tutorial 5

**Comment by darlainedeme** [comment]
> Currently binder examples _05_load_raster.ipynb_ and _32_local_tile.ipynb_ doesn't work. I'm getting error: `ImportError: localtileserver is not installed. Please install it before proceeding. https://github.com/banesullivan/localtileserver`
> 
> I've noticed, that tests related to these functionalities are commented out in [tests/test_leafmap.py](https://github.com/giswqs/leafmap/blob/master/tests/test_leafmap.py#L265)

just 
`!pip install localtileserver`
