### ISSUE TITLE
Matplotlib  palette error

### ISSUE THREAD

**Issue by orttak** [giswqs/leafmap#190]
-   leafmap version: latest
-   Python version: 3.7, 3.8 and 3.9
-   Operating System: In docker ubuntu:20 , python3.7 base image and pangeo notebook

import leafmap
m = leafmap.Map()
dem_path='CGIAR_SRTM90_V4.tif' #same folder with notebook
m.add_local_tile(ndvi_path,palette='matplotlib.Viridis_10',layer_name="NDVI")

I try to install leafmap in docker env and
I got below error when I try add local raster. It could be realted with localtileserver or ipyleaflet but I am not sure which one.

### What I Did
I am working on Win-11 anaconda env. In my local anaconda env, everything is fine but when I try it in docker it doesn't work.

![image](https://user-images.githubusercontent.com/28723856/150672104-0aa41028-2501-4bc6-8199-de544319337f.png)

**Comment by giswqs** [comment]
Use  **viridis**. See https://leafmap.org/notebooks/32_local_tile/

**Comment by orttak** [comment]
m.add_local_tile(dem, palette='viridis', layer_name="DEM") > This sample code works fine in local anaconda env but when I try to use in in docker env which is
 > ubuntu:18
 >install conda
 > your instruction from leafmap
 > I use jupyter notebook, not jupyter lab 

I try with all type of path(I saw from your github comment, we should use relative path) and map seems empty. 


![image](https://user-images.githubusercontent.com/28723856/150680213-dce7783f-7d4a-46fb-bbe8-7d1063ef85ad.png)

**Comment by giswqs** [comment]
This is likely a [localtileserver](https://github.com/banesullivan/localtileserver) issue. Try the following example without using leafmap. If it doesn't work, then it is a localtileserver issue. You might want to try out the [localtileserver docker image](https://github.com/banesullivan/localtileserver#-docker-service) rather than creating y our own docker image.

This issue might also be related to https://github.com/banesullivan/localtileserver-demo/issues/1

```python
from localtileserver import get_leaflet_tile_layer, TileClient
from ipyleaflet import Map

# First, create a tile server from local raster file
tile_client = TileClient('path/to/your/dem.tif')

# Create ipyleaflet tile layer from that server
t = get_leaflet_tile_layer(tile_client)

# Create ipyleaflet map, add tile layer, and display
m = Map(center=tile_client.center())
m.add_layer(t)
m
```

**Comment by orttak** [comment]
You right Sir. it doesn't work with localtileserver sample. I also tried with Binder but it was all same. 
Thank you for your response
