### ISSUE TITLE
Show toolbar button on the map

### ISSUE THREAD

**Issue by redaidrissi92** [giswqs/leafmap#193]
Hello,
I want to know how to show the toolbar button in the top right part of the MapBox

![streamlit](https://user-images.githubusercontent.com/98342153/150829830-3df1be0b-429b-4b85-8875-1282ab4d7f24.png)

**Comment by giswqs** [comment]
What do you mean? The toolbar only supports ipyleaflet. Mapbox is not ipyleaflet.
