### ISSUE TITLE
add_local_tile not adding any tile atleast no tile is getting displayed 

### ISSUE THREAD

**Issue by MATRIX4284** [giswqs/leafmap#197]
### Environment Information

-   0.7.5:
-   3.7:
-   Ubuntu

### Description

Add local tile layer not working.No local tile is getting displayed
### What I Did
import os
import leafmap
m = leafmap.Map()
file1 = os.path.join('/DISK003/SPATIAL_ANALYTICS', 'landuse.tif')

m.add_local_tile(file1,  layer_name="Local COG")
m
```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by giswqs** [comment]
Are you using it locally or on cloud environments?

**Comment by MATRIX4284** [comment]
locally on ubuntu

**Comment by giswqs** [comment]
Leafmap relies on [localtileserver](https://github.com/banesullivan/localtileserver) to load local raster datasets. Try the following example with your own dataset without using leafmap. If it doesn't work, then it is a localtileserver issue. You should [report](https://github.com/banesullivan/localtileserver/issues) it to localtileserver. 

```python
from localtileserver import get_leaflet_tile_layer, TileClient
from ipyleaflet import Map

# First, create a tile server from local raster file
tile_client = TileClient('~/Desktop/TC_NG_SFBay_US_Geo.tif')

# Create ipyleaflet tile layer from that server
t = get_leaflet_tile_layer(tile_client)

# Create ipyleaflet map, add tile layer, and display
m = Map(center=tile_client.center())
m.add_layer(t)
m
```

**Comment by MATRIX4284** [comment]
thanks for the direction.I ran the command and found that the problem remains and it is proved that the problem is with localtileserver.I will close this bug and open a bug in localtileserver.

Regards,
Kaustav
