### ISSUE TITLE
plotly colab import error

### ISSUE THREAD

**Issue by Niko-La** [giswqs/leafmap#199]
![image](https://user-images.githubusercontent.com/14004559/153317822-01cb87dd-0bf6-4cc0-ab2d-3e706945320a.png)

looks like colab is giving issue. 

### Environment Information

-   leafmap version:
-   Python version:
-   Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by giswqs** [comment]
How did you import plotly? I just tested the notebook example, it works fine. 
```python
import leafmap.plotlymap as leafmap
```
https://leafmap.org/notebooks/38_plotly/

**Comment by Niko-La** [comment]
>

**Comment by Niko-La** [comment]
@giswqs followed notebook 38 on colab

**Comment by giswqs** [comment]
You need to restart the kernel after installation.

**Comment by giswqs** [comment]
After restarting the kernel, run the following. 
```python
import leafmap.plotlymap as leafmap
leafmap.update_package()
leafmap.fix_widget_error()
```

**Comment by Niko-La** [comment]
restarting kernel on colab

![image](https://user-images.githubusercontent.com/14004559/153320750-e501e4d1-4169-41f9-aaa1-e23dc1addce0.png)



```
import leafmap.plotlymap as leafmap
leafmap.update_package()
leafmap.fix_widget_error()
```

![image](https://user-images.githubusercontent.com/14004559/153320949-50ab5480-9049-4764-a852-866ca6eb706d.png)

**Comment by giswqs** [comment]
Close your current notebook. Start with a fresh notebook. install the package from GitHub
```
!pip install git+https://github.com/giswqs/leafmap.git
```
Restart the kernel, then

```python
import leafmap.plotlymap as leafmap
leafmap.fix_widget_error()
```

**Comment by GvdDool-SiS** [comment]
Dear Qiusheng Wu,
I see you are applying the fix suggested on the github.com/plotly/plotly.py/issues, which I found as well, and there you are saying that this behaviour also (could) happen in CoLab - will the function also update the CoLab set up, as it tries to update a file? 

I am working both local (and that should be fine), but then sharing with collaborators on CoLab, and that worries me a little as it requires this function to be part of the structure. Would you have any suggestions on how to mitigate this problem until plotly fixes the bug?

**Comment by giswqs** [comment]
@GvdDool-SiS Run the following lines if you experience errors.

```python
import leafmap.plotlymap as leafmap
leafmap.fix_widget_error()
```

**Comment by GvdDool-SiS** [comment]
@giswqs Thanks, I will make a note, and add a comment in the boilerplate when using a plotly scattermapbox element; is this the only time you have seen this ValueError, or are there other elements causing this problem? I hope plotly will fix this "bug", but guess, for now, the workaround will have to do, as this has been known for some time now.
