### ISSUE TITLE
Leafmap (default backend) and Streamlit for vector tile layers

### ISSUE THREAD

**Issue by iwpnd** [giswqs/leafmap#203]
hi 👋 

### Environment Information

-   leafmap version: 0.7.7
-   steamlit version: 1.5.1
-   Python version: 3.9.0
-   Operating System: MacOS

### Description

I want to run leafmap in stream lit with custom vector tile layers. 
The page is displayed but the browser console overflows with errors. Eventually it goes unresponsive with this error looping infinitely:

```bash
Uncaught (in promise) Error: Invalid LatLng object: (53.24878214338736, NaN)
    at new B (leaflet-src.js:1365:11)
    at Object.unproject (leaflet-src.js:1667:12)
    at Object.pointToLatLng (leaflet-src.js:1506:28)
    at n.unproject (leaflet-src.js:3963:29)
    at n.layerPointToLatLng (leaflet-src.js:3971:17)
    at n.containerPointToLatLng (leaflet-src.js:4028:17)
    at n._update (leaflet-src.js:5493:10)
    at n.whenReady (leaflet-src.js:4428:15)
    at n.onAdd (leaflet-src.js:5469:9)
    at n.addTo (leaflet-src.js:4757:44)
```

The error does not occur when falling back to folium instead, so my guess is that I'm not supposed to use the default plotting backend. However folium does not allow me to use `m.add_vector_tile_layer()`. 

### What I Did

Streamlit app

```python
from leafmap import leafmap

m = leafmap.Map(
    center=[53.25, 13.37],
    zoom=8,
    draw_control=False,
    measure_control=False,
    fullscreen_control=True,
    attribution_control=False,
)

m.to_streamlit()
```

**Comment by giswqs** [comment]
Unfortunately, folium does not yet support vector tile layers. Although ipyleaflet supports vector tile layers, it doesn't work well when converting it to streamlit. Essentially, the ipyleafmet Map object is converted to an HTML file. All bidirectional functionality will be lost. There is not much leafmap can do about this unless folium offiically supports vector tile layers. 

- https://github.com/python-visualization/folium/issues/937
- https://github.com/python-visualization/folium/pull/943

**Comment by iwpnd** [comment]
As an FYI @giswqs, I addressed this upstream and added the needed plugin to support it to folium in [#1576](https://github.com/python-visualization/folium/pull/1576). I don't know when and if it will be accepted. In case it is not accepted, what is your take on 3rd party plugins for folium?

**Comment by giswqs** [comment]
@iwpnd If the PR is not accepted upstream, you are welcome to submit it to leafmap, just like what I did in https://github.com/giswqs/leafmap/pull/218

I have been trying to get the SideBySide plugin. However, folium still has not accepted the PR since it was submitted two years ago. Therefore, I adapted the code and added it to leafmap directly. You can do the same if you want to. 
https://github.com/python-visualization/folium/pull/1292
