### ISSUE TITLE
Leafmap figure window does not adjust to height and width specifications on colab

### ISSUE THREAD

**Issue by sugatoray** [giswqs/leafmap#21]
### Environment Information

-   leafmap version: 0.2.0
-   Python version: 3.7.10
-   Operating System: Linux

```python
# code snippet for the above information
def systeminfo():
    import platform

    uname = platform.uname()
    platform_details = platform.platform()

    print(f'leafmap version: {leafmap.__version__}')
    print(f'python version: {platform.python_version()}')
    print(f'operating system: {uname.system}')
    print(f'  details: {platform_details}')

systeminfo()
```

### Description

The figure window for leafmap does not adjust for non-defauilt values of height and width specifications for `leafmap.Map()` method. Please see the screenshot below.

### What I Did

I followed the demo [colab notebook][#demo-colab-notebook]. But when I tried changing the height/width of the visualization, although the size of the map adjusted to my specifications, the figure window remained as wide and big it was without any height/width specification.

[#demo-colab-notebook]: https://colab.research.google.com/github/giswqs/leafmap/blob/master/examples/notebooks/01_leafmap_intro.ipynb#scrollTo=qZoGBUfH1vZw

```python
# ! pip install leafmap -Uqq
import leafmap

m = leafmap.Map(height="450px", width="600px")
m
```
### Screenshot

![image](https://user-images.githubusercontent.com/10201242/121418965-15b9a300-c931-11eb-9509-a8444f4f219e.png)

**Comment by giswqs** [comment]
This is an issue related to folium rather than leafmap. In Colab, leafmap uses folium as the plotting backend. If you try the following code that uses only folium, you will get the same result. I will see I can figure out a solution for this. 

```python
import folium
m = folium.Map(height=450, width=600)
m
```

**Comment by giswqs** [comment]
This bug has been fixed. Run `leafmap.update_package()` in Colab and restart the kernel to take effect. 

![image](https://user-images.githubusercontent.com/5016453/121445524-a3ac8280-c95f-11eb-9ac0-9b075b2111a9.png)

**Comment by sugatoray** [comment]
Yes, I checked at my end and confirmed the same. Thank you, fr the quick resolution.

![image](https://user-images.githubusercontent.com/10201242/121715078-1de61f80-caa4-11eb-943b-2baca0547066.png)
