### ISSUE TITLE
Add support for visualizing LiDAR data

### ISSUE THREAD

**Issue by giswqs** [giswqs/leafmap#212]
References:

- https://github.com/laspy/laspy
- https://github.com/isl-org/Open3D
- https://medium.com/spatial-data-science/an-easy-way-to-work-and-visualize-lidar-data-in-python-eed0e028996c

**Comment by deeplook** [comment]
See also: https://docs.pyvista.org/api/examples/_autosummary/pyvista.examples.downloads.download_lidar.html?highlight=lidar#pyvista.examples.downloads.download_lidar

**Comment by giswqs** [comment]
@deeplook I did not know that pyvista can also visualize LiDAR data. That's cool. The open3d package is huge! 480 MB with the pip wheel. Looks like pyvista would be a good alternative. Thanks.

**Comment by giswqs** [comment]
@deeplook @banesullivan It seems pyvista can read las/laz data directly. The pyvista example uses the vtp format. Is there a way to convert las/laz to vtp?  

https://github.com/pyvista/vtk-data/blob/master/Data/kafadar-lidar-interp.vtp

**Comment by banesullivan** [comment]
PyntCloud works well with PyVista. See https://github.com/daavoo/pyntcloud#integration-with-other-libraries

```py
from pyntcloud import PyntCloud
import pyvista as pv

cloud = PyntCloud.from_file("some_file.ply")

mesh = cloud.to_instance("pyvista", mesh=True)
```

**Comment by giswqs** [comment]
@banesullivan That's great to know. Trying it out. Thanks.

**Comment by banesullivan** [comment]
Make sure you install the `LAS` extras: https://github.com/daavoo/pyntcloud/blob/f07a236871a6fc9a779f467f02e10e4e4e0ab1f3/setup.py#L27

```
pip install pyntcloud[LAS]
```

**Comment by giswqs** [comment]
@banesullivan The pyntcloud documentation is scarce. I am not quite sure how to get it right. By default, it seems to use the last Data Array (`point_source_id` in this case) rather than elevation, resulting in all black when rendered by pyvista. 

Open3D can render it correctly, but Open3D does not support adding a colorbar. https://github.com/isl-org/Open3D/issues/2147

[Here](https://www.whiteboxgeo.com/sample_data/StElisAk.zip ) is the sample dataset I used. 

![image](https://user-images.githubusercontent.com/5016453/156431487-6a2668c6-481e-41c9-a09a-a63643eca14f.png)

Rendered by pyvista
![image](https://user-images.githubusercontent.com/5016453/156431595-7e94bf2f-8c9f-418e-99e9-eeb2c92e6399.png)

Rendered by Open3D

```python
geom = o3d.geometry.PointCloud()
geom.points = o3d.utility.Vector3dVector(point_data)
o3d.visualization.draw_geometries([geom])
```
![image](https://user-images.githubusercontent.com/5016453/156431778-802b8959-46db-4669-ae38-af850cc27b4b.png)

**Comment by banesullivan** [comment]
I suspect o3d is computing that elevation itself. We could do the same in PyVista:

```py
mesh = mesh.elevation()
mesh.plot(scalars='Elevation' cmap='terrain')
```

**Comment by giswqs** [comment]
Wow, that did the trick! Many thanks. 

![image](https://user-images.githubusercontent.com/5016453/156434498-f9e58c51-56dc-4f10-8b02-fe591f8a7c16.png)

**Comment by giswqs** [comment]
Add Eye Dome Lighting features to improve point cloud rendering

https://docs.pyvista.org/examples/02-plot/edl.html

**Comment by giswqs** [comment]
The `eye_dome_lighting` param has been added.
