### ISSUE TITLE
Duplicated indices in a DataFrame leads to the failure of add_points_from_xy().

### ISSUE THREAD

**Issue by gladcolor** [giswqs/leafmap#220]
### Environment Information

-   leafmap version:  0.8.2
-   Python version: 3.7.10
-   Operating System: Windows

### Description

Describe what you were trying to get done.
Duplicated indices in a DataFrame lead to the failure of add_points_from_xy().

**Comment by giswqs** [comment]
Not enough of information for debugging. Please provide sample data and script that can reproduce the issue

**Comment by giswqs** [comment]
Closing this issue to the lack of information. Feel free to reopen when you can provide detailed information
