### ISSUE TITLE
Help with netcdf files

### ISSUE THREAD

**Issue by mathomp4** [giswqs/leafmap#231]
### Environment Information

-   leafmap version: 0.9.1
-   Python version: 3.9.10
-   Operating System: macOS 10.6.5

### Description

I was trying to follow along with the [netCDF example](https://leafmap.org/notebooks/52_netcdf/), but with my own netCDF file. 

But when I do that, I get an error:
```python
AttributeError: 'Dataset' object has no attribute 'rio'
```

### What I Did

```python
import leafmap
filename = "test.nc4"
data = leafmap.read_netcdf(filename)
m = leafmap.Map(layers_control=True)
tif = 'wind_global.tif'
leafmap.netcdf_to_tif(filename, tif, variables=['U', 'V'], shift_lon=True)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [27], in <module>
----> 1 leafmap.netcdf_to_tif(filename, tif, variables=['U', 'V'], shift_lon=True)

File ~/GEOSpyD/4.10.3_py3.9/2022-02-14/lib/python3.9/site-packages/leafmap/common.py:5350, in netcdf_to_tif(filename, output, variables, shift_lon, lat, lon, return_vars, **kwargs)
   5348     xds.rio.set_spatial_dims(x_dim=lon, y_dim=lat).rio.to_raster(output)
   5349 else:
-> 5350     xds[variables].rio.set_spatial_dims(x_dim=lon, y_dim=lat).rio.to_raster(output)
   5352 if return_vars:
   5353     return output, allowed_vars

File ~/GEOSpyD/4.10.3_py3.9/2022-02-14/lib/python3.9/site-packages/xarray/core/common.py:239, in AttrAccessMixin.__getattr__(self, name)
    237         with suppress(KeyError):
    238             return source[name]
--> 239 raise AttributeError(
    240     f"{type(self).__name__!r} object has no attribute {name!r}"
    241 )

AttributeError: 'Dataset' object has no attribute 'rio'

```
Note that in my test file, I have `U` and `V` not `u_wind` and `v_wind`. 

I also tried the `m.add_netcdf()` version, but it died with essentially the same error. 

I'm not that good at Python, I just saw this project and thought, I want to try it out! :)

**Comment by giswqs** [comment]
Did you install `rioxarray`? See the required packages at the beginning of the notebook.

```
pip install leafmap xarray rioxarray netcdf4 localtileserver
```

**Comment by mathomp4** [comment]
Well, huh. I did:
```
mamba install leafmap
```
thinking `mamba` (aka fast `conda`) would get all the dependencies. Nope! So doing:
```
mamba install leafmap xarray rioxarray netcdf4 localtileserver
```
found I was missing both `rioxarray` and `localtileserver`.

So that fixed that...and then I hit another issue:
```
TooManyDimensions: Only 2D and 3D data arrays supported.
```
The files my model produces have variables of lat,lon,time.

I *think* you can do `data.isel(time=0,drop=True)` to remove the time from an xarray set, but is there a way to pass that "knowledge" along to leafmap?

**Comment by giswqs** [comment]
I am not an expert on netcdf or xarray yet. Would you like to submit a pull request? Under the hood, the NetCDF file is converted to GeoTIFF. 

https://github.com/giswqs/leafmap/blob/4e3bc687ffd973cf1c483f12f5804d7b088e9b53/leafmap/common.py#L5290

**Comment by mathomp4** [comment]
> I am not an expert on netcdf or xarray yet. Would you like to submit a pull request? Under the hood, the NetCDF file is converted to GeoTIFF.
> 
> https://github.com/giswqs/leafmap/blob/4e3bc687ffd973cf1c483f12f5804d7b088e9b53/leafmap/common.py#L5290

@giswqs Well, you are more an expert than I! Still, I might ping a Python guru I know here. Maybe if he has time he can figure it out...

**Comment by mathomp4** [comment]
@giswqs Well, I got something to work. See #232. Make sure it doesn't break any of your code, of course!
