### ISSUE TITLE
VectorTileLayer support for ipyleaflet

### ISSUE THREAD

**Issue by nahidpervez** [giswqs/leafmap#24]
### Description
Thanks for putting this together! this seems to have a great collection of tools required for geospatial analysis.
I was wondering if vector tile layer (https://ipyleaflet.readthedocs.io/en/latest/api_reference/vector_tile.html#) can be added to this?

### Source code

```python
# may be something like this
m = leafmap.Map()
m.add_vector_tile_layer(url="https://tile.nextzen.org/tilezen/vector/v1/512/all/{z}/{x}/{y}.mvt?api_key={apiKey}", name="VectorTileLayer")
```

**Comment by nahidpervez** [comment]
@giswqs : any idea when it will be part of the release in pypi and conda ?

**Comment by giswqs** [comment]
v0.2.0 was just released a few days ago. I plan to add a few more new features and make a new release sometime next week. For the time being, you can run `leafmap.update_package()` within Jupyter to install the latest version from GitHub.

**Comment by giswqs** [comment]
@nahidpervez For the `add_vector_tile_layer` function you contributed, do you have a working notebook example for using the function? If seems an API key is needed to access nextzen vector tile layers. Do you have any other vector tile layer URL without needing an API key?

**Comment by nahidpervez** [comment]
@giswqs Good point, let me make some modification to get the API key as well. That will make the feature more robust.

**Comment by nahidpervez** [comment]
@giswqs : https://github.com/giswqs/leafmap/pull/26

**Comment by nahidpervez** [comment]
@giswqs I think we can mark this one as complete 🥳
