### ISSUE TITLE
add_points_from_xy() raise AttributeError if the input dataframe contains column names not supported by namedtuples

### ISSUE THREAD

**Issue by junjiez** [giswqs/leafmap#248]
### Environment Information

-   leafmap version: 0.9.3
-   Python version: 3.8
-   Operating System: Windows 10

### Description

Tested add_points_from_xy() using dataframes with column names that are not supported by `namedtuples` (e.g., starts with "_" or has space). It will raise AttributeError (like: 'Pandas' object has no attribute <column_name>) in the line generating html for popup_html:

```python
for row in df.itertuples():
        html = ""
        for p in popup:
            html = html + "<b>" + p + "</b>" + ": " + str(getattr(row, p)) + "<br>"
```

In `df.itertuples()`, the column names not supported by `namedtuples` will be automatically renamed (e.g., '_col1' will be change to '_0'). And in `getattr(row, p)`, it will not be able to retrieve the attribute with the original column name. 

### What I Did

A code example to track which fields have changed by `namedtuples`

```
from collections import namedtuple

columns = ["_col1", "_col2", "column name", "col4"]
a = namedtuples("Table", columns, rename=True)

old_fields = columns
new_fields = a._fields

mapper = {}
for f1, f2 in zip(old_fields, new_fields):
    mapper[f1] = f2

print(mapper)
```
> {"_col1": "_0", "_col2": "_1", "column name": "0_2", "col4": "col4"}

### Solutions

A quick solution would be changing `df.itertuples()` to `df.iterrows()` and corresponding `str(getattr(row, p))` to `str(row[p])` or suggest users to rename the dataframe columns which are not supported by `namedtuples`.

The code block in `foliumap.py` to be changed for example:
```python
for idx, row in df.iterrows():
    html = ""
    for p in popup:
        html = html + "<b>" + p + "</b>" + ": " + str(row[p]) + "<br>"
    popup_html = folium.Popup(html, min_width=min_width, max_width=max_width)

    if items is not None:
        index = items.index(row[color_column])
```

**Comment by giswqs** [comment]
Thanks for reporting. Would you like to submit a pull request so that you can get credit for this?

**Comment by junjiez** [comment]
Hi Qiusheng,

So nice to have your reply! Your geospatial python libraries are so useful!

BTW, a brief introduction of myself. My name is Junjie Zhang. I have a
background in geoinformation science and had my bachelor from Wuhan
University.

The geospatial python libraries you have created. I was amazed when I came
across them and found your webpage online. They are so useful and fill some
gaps that are long-existing in the GIS field. You have created such
wonderful tools and made such great contributions to the community!

Hope to connect with you and hope to continue to contribute to the project.

Best regards,
Jason
