### ISSUE TITLE
Doesn't display all items in KML file when loaded

### ISSUE THREAD

**Issue by mbegnaud** [giswqs/leafmap#252]
### Environment Information

-   leafmap version: latest 0.9.3
-   Python version: 3.7.10
-   Operating System: ubuntu

### Description

Have existing KML files with points, paths, and polygons. leafmap is only showing some of the points and not preserving the style defined for them.

### What I Did

Was getting an error when just using "m" to display the map.

```
import leafmap.foliumap as leafmap
m = leafmap.Map(
    draw_control=False, measure_control=True, fullscreen_control=False, attribution_control=False, 
    center=[21, 103], zoom=6
)
m.add_basemap("Esri.NatGeoWorldMap")
m.add_tile_layer(url="https://mt1.google.com/vt/lyrs=y&x={x}&y={y}&z={z}", name="Google Satellite", attribution="Google",)
in_kml = 'Results/Laos615386657.RSTT.kml'
m.add_kml(in_kml, layer_name="Laos615386657")
m.static_map()
```

**Comment by giswqs** [comment]
Closing this issue for now. Feel free to reopen it if you are still experiencing issues.
