### ISSUE TITLE
add_xy_data() doesn't seem to work in Streamlit 

### ISSUE THREAD

**Issue by GaiaGrower** [giswqs/leafmap#261]
I'm trying to run leafmap from within Streamlit.  I notice that I get no output when using the add_xy_data() function.
Please see below.  I can get a map when that line is commented out, but not when I leave it in.
It works great in a jupyter notebook.  There are no error messages, just no map.

# Example problem
import streamlit as st
import leafmap.foliumap as leafmap
from bqplot import Tooltip

def app():

    inCsv = r"C:\Projects\DataViz\WorldGame\EarthDashboard\Extinction\ExtinctWikiSrchd\extinctsWiki.csv"

    myMap = leafmap.Map()

    # Create a point layer from a CSV file containing lat/long information.
    # This works great in a jupyter notebook.  When used within Streamlit, no map is produced
    #myMap.add_xy_data( inCsv, x="Longitude", y="Latitude", label="Species", layer_name="World Cities" )

    myMap.add_basemap( "OpenTopoMap" )
    myMap.info_mode="on_hover"

    myMap.to_streamlit()

**Comment by giswqs** [comment]
This function is for ipyleaflet only. It won't work with streamlit. See https://github.com/giswqs/streamlit-geospatial/blob/master/apps/xy.py

**Comment by GaiaGrower** [comment]
Yessir!  The add_points_from_xy() function with a "cleaned up" dataframe
works great!
Thank you for taking the time to answer my question.
Baruch Bashan
