### ISSUE TITLE
Run 01_leafmap_intro.ipynb on google colab nothing is plotted

### ISSUE THREAD

**Issue by dustming** [giswqs/leafmap#268]
### Environment Information

-   leafmap version:
-   Python version:
-   Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Run 01_leafmap_intro.ipynb on google colab nothing is plotted
```

**Comment by giswqs** [comment]
see https://github.com/giswqs/geemap/issues/1132#issuecomment-1179673334

**Comment by dustming** [comment]
> see [giswqs/geemap#1132 (comment)](https://github.com/giswqs/geemap/issues/1132#issuecomment-1179673334)

Got it, Just saw the comment and it works~!!! This is amazing work!!! 

I tried to use leafmap to plot a huge polygon dataset in google colab. it ended without error but nothing plotted. 

Are you interested in test this large polygon dataset?

**Comment by dustming** [comment]
Here is the link for the large [dataset.](https://drive.google.com/u/0/uc?id=1Qkx2fMi6Nl2Qs4SaB2NKG5pCTmIQ77Vl&export=download)

 I got an unknown problem when I tried to plot "finalcat_info.shp"

The same code works for a small watershed as shown in the following: 

![image](https://user-images.githubusercontent.com/40034156/178149950-8b9306de-36a0-4370-92c3-b3f06e3fb1f9.png)

Thanks for all your amazing work!!!

**Comment by giswqs** [comment]
ipyleaflet can only handle relatively small datasets. For large datasets, you might need to host it on a server and access it through web services.

**Comment by giswqs** [comment]
Yes, you can certainly use a for-loop, but the map will eventually become non-responsive when adding too much data to the map.
