### ISSUE TITLE
Read netcdf from variable

### ISSUE THREAD

**Issue by mn5hk** [giswqs/leafmap#271]
### Description

I am trying to read netCDF into leafmap. While it works very well with the "*.nc" file, the current version does not support reading netCDFs (xarray files) from a variable.

Implementing the code below in the current version results in the following error: 
AttributeError: 'Dataset' object has no attribute 'startswith'

### Source code

```
m.add_netcdf(netCDF_variable, 
            variables = ['variable_name'],
            palette = 'coolwarm',
            shift_lon = True)
```

**Comment by giswqs** [comment]
Leafmap relies on localtileserve to display raster data. Localtileserver can't display xarrays directly. The input needs to be physical files, such as GeoTIFFs. You need to convert xarrays to GeoTIFFs to be displayed on the map. 

https://geemap.org/notebooks/105_netcdf/
