### ISSUE TITLE
GeoJSON features are not displaying on the map

### ISSUE THREAD

**Issue by philvarner** [giswqs/leafmap#274]
### Environment Information

-   leafmap version: 0.10.2 (I saw same behavior with 0.9.x)
-   Python version: 3.9.12
-   Operating System: MacOS

requirements.txt from pip freeze also attached.

### Description

I'm trying to add some geojson polygons to a map, but they don't appear. I tried the [geojson example](https://leafmap.org/notebooks/00_key_features/#add-geojson) and that doesn't work for me either. 

### What I Did

I ran the [geojson example](https://leafmap.org/notebooks/00_key_features/#add-geojson) and got the following output (see that the cable lines are not displayed). I also tried this with a dict representing a polygon and it also did not display.

<img width="861" alt="image" src="https://user-images.githubusercontent.com/124996/179770551-ecb4344b-1614-497a-9fe8-c13e5625ddf2.png">

[requirements.txt](https://github.com/giswqs/leafmap/files/9141733/requirements.txt)

**Comment by giswqs** [comment]
It works fine on my Linux machine. Try creating a fresh conda env to install leafmap. 

```bash
    conda create -n geo python=3.9
    conda activate geo
    conda install mamba -c conda-forge
    mamba install leafmap geopandas -c conda-forge

```

**Comment by philvarner** [comment]
The conda directions worked. I wonder what the difference between that and my venv with pip install is? I'll look into this further.
