### ISSUE TITLE
install leafmap on google colab 

### ISSUE THREAD

**Issue by dustming** [giswqs/leafmap#279]
### Environment Information
Google colab.

### Description
I got the following error when I tried to use the leafmap on google colab. 
![image](https://user-images.githubusercontent.com/40034156/185165455-db2fba8e-b3b2-4b6b-80b0-5a68570e8dfe.png)

### What I Did

```
!pip install leafmap
```

**Comment by giswqs** [comment]
You can ignore all the warnings. Restart the runtime. Everything should work just fine. 
![image](https://user-images.githubusercontent.com/5016453/185167648-fd2345f2-efb3-4673-9bce-ea85247026d6.png)

**Comment by dustming** [comment]
Hi Prof. Wu
  
   I see. I got a weird error in my script after I "!pip install leafmap". The script worked two days ago. But today, the script gives a "IndexError: list index out of range" error. It happened when I tried to obtain centroid x and y using geopandas ".geometry.centroid.y" .  

  This error is gone if I do not install leafmap.  

  Do you have any suggestions for this error? 

  It might be something wrong with my script. 

Thanks
Ming

**Comment by giswqs** [comment]
Could you provide the script and data that can reproduce the error?

**Comment by dustming** [comment]
Here is the link https://colab.research.google.com/drive/1OXiq5hOafaFWNqv_S7Gg5SgGbqr239dD?usp=sharing

By skipping this section, the error disappears in the rest section: 
![image](https://user-images.githubusercontent.com/40034156/185177057-7f0ab584-04c7-4b5d-9775-c9db90642a83.png)

Thanks so much.
Ming

**Comment by dustming** [comment]
Thanks all the same. the leafmap was used in the last section to plot the
result.
best
ming
