### ISSUE TITLE
Better documentation and approach for rescale parameter for multi-band COGs

### ISSUE THREAD

**Issue by philvarner** [giswqs/leafmap#284]
### Description

Two requests:

(1) multi-band COGs frequently need different rescaling for different bands. How to do this isn't documented in the API, but this
works because of how requests handles the params dictionary:

```
m.add_cog_layer(url, rescale=["164,223","130,211","99,212"])
```

so that `rescale=164,223&rescale=130,211r&rescale=99,212` is sent to the tiler endpoint.

Maybe this should be documented? (this works with titiler, though I don't know enough about the tiler api to know if it works on all tilers)

(2) 

When `rescale` is not supplied as an argument, the rescaling is done across all bands:

```
    if "rescale" not in kwargs:
        stats = cog_stats(url, titiler_endpoint)
        if "message" not in stats:
            percentile_2 = min([stats[s]["percentile_2"] for s in stats])
            percentile_98 = max([stats[s]["percentile_98"] for s in stats])
            kwargs["rescale"] = f"{percentile_2},{percentile_98}"```
```

whereas this should (at least) only over the bands specified via `bands` or `bidx`. Even better would be to specify as above (`rescale=["164,223","130,211","99,212"]`) so that the rescaling is done per band.

**Comment by giswqs** [comment]
Good suggestions. Would you like to submit a PR so that you can get credits for this?

**Comment by philvarner** [comment]
sorry I can't, I have many other open source items to do on my list ahead of this.
