### ISSUE TITLE
User not specified (leafmap.connect_postgis function)

### ISSUE THREAD

**Issue by REDADRISSI** [giswqs/leafmap#292]
I tried this code to load a shapefile into my web app (Streamlit), i got this error after running the code :

> ValueError: user is not specified.
> Traceback:
> File "c:\users\pc\pycharmprojects\webgis_cad\venv\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 556, in _run_script
>     exec(code, module.__dict__)
> File "C:\Users\pc\PycharmProjects\WebGIS_CAD\main.py", line 56, in <module>
>     database="IFE_WEBGIS", host="localhost", user="postgres", password="XXXXXXXXX", use_env_var=True
> File "c:\users\pc\pycharmprojects\webgis_cad\venv\lib\site-packages\leafmap\common.py", line 1791, in connect_postgis
>     raise ValueError("user is not specified.")

the code used : 
`con = leafmap.connect_postgis(
        database="IFE_WEBGIS", host="localhost", user="postgres", password="XXXXXXXXX", use_env_var=True
    )`

Thank you,

**Comment by giswqs** [comment]
Did you try it in a notebook environment without using streamlit?

**Comment by REDADRISSI** [comment]
Yes, i’ve got the same error in both.
