### ISSUE TITLE
Choropleth not working 

### ISSUE THREAD

**Issue by jfragosojanuario** [giswqs/leafmap#296]
### Environment Information

-   leafmap version: 0.10.6
-   Python version: Python 3.8.0
-   Operating System: MacOS

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

I'm trying to get a Choropleth map using leafmap, from [this example](https://leafmap.org/notebooks/53_choropleth/) , but it is not working because of the classify module in mapclassifiers. 

I'm getting the following error: 

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-e18c41de95af> in <module>
      1 m = leafmap.Map()
      2 m.add_data(
----> 3     data, column='POP_EST', scheme='EqualInterval', cmap='Blues', legend_title='Population'
      4 )
      5 m

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/leafmap/leafmap.py in add_data(self, data, column, colors, labels, cmap, scheme, k, add_legend, legend_title, legend_kwds, classification_kwds, layer_name, style, hover_style, style_callback, info_mode, encoding, **kwargs)
   3371             k=k,
   3372             legend_kwds=legend_kwds,
-> 3373             classification_kwds=classification_kwds,
   3374         )
   3375 

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/leafmap/common.py in classify(data, column, cmap, colors, labels, scheme, k, legend_kwds, classification_kwds)
   5797         classification_kwds["k"] = k
   5798 
-> 5799     binning = mapclassify.classify(
   5800         np.asarray(values[~nan_idx]), scheme, **classification_kwds
   5801     )

AttributeError: module 'mapclassify' has no attribute 'classify'

----------------

However, according to [mapclassify API](https://pysal.org/mapclassify/api.html), the classify method exists. Could this be a version issue? Is there any fiz for this? 

Many thanks in advance. 

Best,
João

**Comment by sackh** [comment]
what is the version of mapclassify? It is working for me with
leafmap==0.10.6 & mapclassify==2.4.3

**Comment by giswqs** [comment]
Have you resolved the issue? Feel free to reopen the issue if you are still experiencing issues after updating mapclassify.
