### ISSUE TITLE
Add here map widget for jupyter as one of the backend.

### ISSUE THREAD

**Issue by sackh** [giswqs/leafmap#3]
### Description

I think [here map widget for jupyter](https://github.com/heremaps/here-map-widget-for-jupyter). will be good addition to this library.
Let me know if you want to add here map widget for jupyter in `leafmap`, I am happy to contribute.

**Comment by giswqs** [comment]
That would be awesome! Pull requests are welcome.

**Comment by sackh** [comment]
closing this as implementation is done in #20
