### ISSUE TITLE
Update intro-notebook to allow figure window resizing in colab 

### ISSUE THREAD

**Issue by sugatoray** [giswqs/leafmap#30]
### Description

The fix for #21 should be incorporated in the [intro-notebook](https://githubtocolab.com/giswqs/leafmap/blob/master/examples/notebooks/01_leafmap_intro.ipynb).

### Source code

I have added the following in the notebook and will submit it in new pull request.

```python
## Run this cell once and then 
## comment it out after first run
import leafmap
leafmap.update_package()
print("Restarting notebook server...")
import os
os.kill(os.getpid(), 9)
```

### Suggested change

![image](https://user-images.githubusercontent.com/10201242/121741931-c906d100-cac4-11eb-83f8-5eda29e76922.png)

**Comment by giswqs** [comment]
`leafmap_update_package()` is only needed for new features that have been released to PyPI and conda-forge. Running `leafmap_update_package()` in every notebook is discouraged as it will reinstall all the dependencies and this could result in issues for some users.
