### ISSUE TITLE
m.to_html('test.html') error

### ISSUE THREAD

**Issue by Niko-La** [giswqs/leafmap#304]
How do we export our rendered map to html?

<img width="636" alt="image" src="https://user-images.githubusercontent.com/14004559/201054491-73642770-7bf9-444b-ae0a-34e5831847b7.png">

edit:
getting the same error when trying to do it via whitetoolgui

**Comment by giswqs** [comment]
What version are you using? It works fine my end, but ipyleaflet and folium backends.

**Comment by giswqs** [comment]
Closing this issue for now. Feel free to reopen if needed.
