### ISSUE TITLE
ability to select location of cholorpeth legen (lefttop,leftbottom,rightbottom,bottomcenter, etc)

### ISSUE THREAD

**Issue by Niko-La** [giswqs/leafmap#305]
The current default location of the legend is interfering with whitetoolgui access 
feature request
1) ability to select location during the `m.add(gdf,....., legend_location ='bottomleft')` 
2)ability to move the legend after ployment to organize before export to html

<img width="324" alt="image" src="https://user-images.githubusercontent.com/14004559/201057683-bbe1194d-3513-41cf-9826-708f723c105b.png">

when having two cholorpeth layers this is an even bigger issue.

edit: https://leafmap.org/notebooks/53_choropleth/  has a moveable one by default? how is this is the leafmap package not the same one? do i need to update it manually? i tried to `leafmap.update_package()` and try by restarting runtime but not getting the same effects

same with the layer info it is not attached to one part of the screen but rather follows the maps

edit2: ran your 53 cholorpeth map on colab and it became fixed just like mine, so maybe it's colab? binder jupyter didn't work `Error displaying widget: model not found`

<img width="688" alt="image" src="https://user-images.githubusercontent.com/14004559/201064538-1999c199-14c7-45c8-b4f6-8aa7436e11f3.png">

<img width="688" alt="image" src="https://user-images.githubusercontent.com/14004559/201065764-3479a559-3ffa-406d-a600-30148ebff657.png">

**Comment by giswqs** [comment]
The legend for folium is movable, while the legend for ipyleaflet is not movable. Binder might have some issues with installing ipyleaflet. For ipyleaflet, the legend height and position can be customized. You can also make the map fullscreen so the components do not overlap. 

https://leafmap.org/leafmap/#leafmap.leafmap.Map.add_legend

**Comment by Niko-La** [comment]
Tried to run folium
![image](https://user-images.githubusercontent.com/14004559/202033502-f9cb7635-da2e-44c8-ba65-8d9ed1a13e2d.png)

Worked fine with the started code

but my working ipyleaflet code is giving the following error on folium backend

![image](https://user-images.githubusercontent.com/14004559/202033730-fe5a1cd6-bba8-4fcb-b115-467199e412b7.png)

It was working as expected on ipyleaflet with the same code

**Comment by giswqs** [comment]
This is likely an issue caused by your data. I just tried out the[ notebook example](https://leafmap.org/notebooks/53_choropleth/). Both the ipyleaflet and folium backends work fine.

**Comment by Niko-La** [comment]
> 
Ok i will investigate my data and reproduce it using the notebook example as the reference file.


I tried kepler backend

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-23-4833d09b646d>](https://localhost:8080/#) in <module>
      5 #m.add_data(gdf, column='Median Total Household Income 2020', scheme='Quantiles', cmap='Blues', legend_title='Median totalHousehold Income 2020', layer_name = "Income")
      6 #m.split_map(left_layer="SATELLITE", right_layer="nlmaps.water")
----> 7 m.add_data(gdf, column='Average Household Size 2021', scheme='Quantiles', cmap='Reds', legend_title='Ave House ppl 2021', layer_name = "House Size", )
      8 m
      9 

TypeError: add_data() got an unexpected keyword argument 'column'
```

same code that was working for default backend.  Technically the code should be identical when changing backend correct?

**Comment by giswqs** [comment]
Not necessarily. Not all backends support the same arguments.
