### ISSUE TITLE
Measure distances and area tool bugging? 

### ISSUE THREAD

**Issue by PennyJClarke** [giswqs/leafmap#311]
The measure distances and area tool appears to have a bug when used in Jupyter notebook, has anyone else experienced an issue?

When I click on the map to begin a measurement the screen shifts on each click? This video demonstrates the issue:

https://user-images.githubusercontent.com/93473831/202700247-cc343b03-d62a-4233-a035-2b9b76ae4346.mp4

This error occurs on the basemap, without having added additional layers, ruling out a projection issue.
I also created a new environment containing only Leafmap, to confirm it was not a package conflict, and the error still occurs.

The use of the measure tool is integral to my use of Leafmap, I thank you for any time, support and guidance you can offer.

**Comment by giswqs** [comment]
This is likely an ipyleaflet issue. Try out the code example below to see if you have the same issue. 

https://ipyleaflet.readthedocs.io/en/latest/controls/measure_control.html

**Comment by PennyJClarke** [comment]
Thank you Qiusheng for suggesting I check the above example code. You are correct, that the error is stemming from ipyleaflet. This is very helpful. 

I have raised an issue on the ipyleaflet github issues page, however, based on your expertise, could offer any guidance on why this may be occurring and if it is a simple bug to fix? Thank you for your guidance and support.

**Comment by giswqs** [comment]
Closing this one since the bug has been reported at https://github.com/jupyter-widgets/ipyleaflet/issues/1076. There is not much I can do about this. As a workaround, you can try the folium backend using `import leafmap.foliumap as leafmap`
