### ISSUE TITLE
'No such comm' Warnings

### ISSUE THREAD

**Issue by Insighttful** [giswqs/leafmap#327]
### Environment Information

-   leafmap version: 0.14.0
-   jupyterlab version = 3.5.0
-   notebook = 6.5.2-e60ab42
-   Python version: 3.10.6
          Available kernels:
            python3        /home/....venv/share/jupyter/kernels/python3
            xpython        /home/.../.venv/share/jupyter/kernels/xpython
            xpython-raw    /home/.../.venv/share/jupyter/kernels/xpython-raw
-   Operating System: Ubuntu 22.04.1 LTS

### Description

When run with the default python3 jupyter kernel, "No such comm" errors are displayed under the map. If an alternate kernel such as xpython is used, these errors do not display.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

```python
m = leafmap.Map(
    draw_control=False,
    measure_control=False,
    fullscreen_control=False,
    attribution_control=True,
)
m.add_basemap(basemap)
m.add_gdf(y[1], layer_name="Addresses")
m
```

![image](https://user-images.githubusercontent.com/116014557/205933650-80906a45-e6a2-4aa6-962f-e00016fa6dad.png)

**Comment by giswqs** [comment]
This might be caused by other dependencies in your existing conda env. I just tried it in a fresh conda env with Python 3.10, and everything works fine. I would suggest you create a fresh conda env to install leafmap.

**Comment by giswqs** [comment]
```bash
conda create -n py310 python="3.10"
conda activate py310
conda install mamba -c conda-forge
mamba install leafmap -c conda-forge
```

**Comment by giswqs** [comment]
You can also use `pip install leafmap`. I have not used poetry before.

**Comment by Insighttful** [comment]
Thank you.

Closing as likely caused by conflicts w/ other dependencies.
