### ISSUE TITLE
Add support for add_colormap for folium backend

### ISSUE THREAD

**Issue by suryaya** [giswqs/leafmap#329]
Hello,

Are there any plans to support the add_colormap function to the folium backend? It would be great to use this with folium.

Thanks,

**Comment by suryaya** [comment]
Thank you! ipyleaflet is buggy for me, so being able to add a vertical colormap to folium would be awesome.

**Comment by giswqs** [comment]
It has been implemented. 

![image](https://user-images.githubusercontent.com/5016453/209267371-092a02e8-b5d0-4c56-b314-66c3b0509618.png)

![image](https://user-images.githubusercontent.com/5016453/209267398-bf3d0d7a-5261-43a9-b611-648e1c0b3dac.png)

![image](https://user-images.githubusercontent.com/5016453/209267411-28f5275d-b2f4-411d-b1f6-63bea39c71be.png)

**Comment by suryaya** [comment]
Thanks so much!
