### ISSUE TITLE
Export to html not working right

### ISSUE THREAD

**Issue by ivo133** [giswqs/leafmap#331]
### Environment Information

-   leafmap version: 0.14.0
-   Python version: 3.10.7
-   Operating System: Win 10
-  Jupyter version: 6.5.2

### Description

Please assist with:
I was trying to save a map to .html and while it does that when I open the html in a new tab or browser it gets quite buggy.
Doesn't display background maps. Can't load the raster layer as well.
Please let me know what I can do to solve this issue...

Thanks

### What I Did

import leafmap as lfm
import pandas as pd
import numpy as np
import geopandas as gpd
import branca.colormap as cm
from shapely.geometry import Point, Polygon, shape
from IPython.core.display import display, HTML, clear_output
import os
import sys
from geopandas import GeoDataFrame as gdf
Lmap = lfm.Map(google_map="HYBRID",center=[42.144378, 24.881488], zoom=15)
dir = 'C:\\Users\\Iwo\\Desktop\\New folder' # local path
Ortho = os.path.join(dir,'katunica-ortho.png') ## The function 'ImageOverlay' loads images from a url and would therefore have trouble loading image from local path
Lmap.add_raster(Ortho, layer_name='UAV')
soil = gpd.read_file(r'D:\RST-Data-Materials\piper_po4vi.geojson') # local path
InSitu=pd.read_csv(r'D:\RST-Data-Materials\insitu10082022.csv',usecols= ['Date','PH(cm)','Chlorophyl','LAI']) # local path
GPS=gpd.read_file(r'D:\RST-Data-Materials\UAV piper\Result-mihaela\katunica_piper-GCP\pole_2021\11.08staro.shp') # local path
GPSgdf= gdf(GPS)
GPSgdf.crs ='epsg:32635'
GPStrans=GPSgdf.to_crs('EPSG:4326')
Lmap.add_point_layer(GPStrans, popup="Name")
Lmap.add_vector(r'D:\RST-Data-Materials\piper_po4vi.geojson', layer_name='Soil') # local path
Mdata = gpd.read_file(r'D:\RST-Data-Materials\UAV piper\Result-mihaela\mask3.geojson') # local path
Lmap.add_vector(r'D:\RST-Data-Materials\UAV piper\Result-mihaela\mask3.geojson',layer_name='mask') # local path
Lmap.to_html('LeafMap.html')

**Comment by giswqs** [comment]
This is an ipyleaflet issue rather than leafmap. The ipyleaflet's to html functionality is buggy. You can try out the folium backend using `import leafmap.foliumap as leafmap`. Both `to_html()` methods inherit from ipyleaflet/folium. There is not much leafmap can do about this.
