### ISSUE TITLE
Input data from OGCAPI endpoints

### ISSUE THREAD

**Issue by KoalaGeo** [giswqs/leafmap#335]
### Description

Allow simple connection to be vector data served from OGCAPI-Features endpoints.  Potentially also OGCAPI-Tiles similar to WMS function.

Imagined functionality:
User provides `endpoint` and `collection` or juster endpoint to the collection - https://ogcapi.bgs.ac.uk/collections/bgsgeology625kbedrock

### Source code

Potentially use OWSLib package to pull data?

**Comment by giswqs** [comment]
Ipyleaflet/folium doesn't seem to support Web Feature Service (WFS) yet. There's not much I can do about it. If you have a working example, please share. I would be happy to integrate it into leafmap.

https://github.com/jupyter-widgets/ipyleaflet/issues/442

**Comment by giswqs** [comment]
Neither ipyleaflet or folium supports WFS yet. Closing this for now. Will revisit this when it becomes possible.
