### ISSUE TITLE
draw_control: annotation tools

### ISSUE THREAD

**Issue by PennyJClarke** [giswqs/leafmap#341]
### Environment Information

-   leafmap [version: 0.10.5 (I am using a downgraded version of ipyleaflet 0.17.0, due to a bug in the measure tool, but even prior to the downgrade from 0.17.2, I had the same issues detailed here).
-   Python version: 3.8.13
-   Operating System: Windows 10

### Description

The 'draw a circle marker', 'draw a marker' and 'draw a circle' all produce the same 'draw a marker annotation. Not the individual style of marker? I need these tools individually particularly the 'draw a circle marker' as a point annotation rather than a balloon shaped 'draw a marker'.

### What I Did

import leafmap
from localtileserver import get_leaflet_tile_layer, TileClient

m = leafmap.Map(layers_control= True, measure_control = True)

The map appears and the following video demonstrates the issues, where the 'circle marker', 'draw a marker' and 'draw a circle' all produce the same 'draw a marker annotation?

https://user-images.githubusercontent.com/93473831/212140103-91ce3152-abe3-4f61-8d7f-d91b0aa1c27a.mp4

In the source code file (C:\Anaconda3\envs\environment\Lib\site-packages\leafmap) I can see this:
![image](https://user-images.githubusercontent.com/93473831/212139894-a9a1e597-05a2-4816-b11e-d79be9d6b24e.png)

**Comment by PennyJClarke** [comment]
Thank you @giswqs you are correct this is an ipyleaflet issue. I found guidance on the ipyleaflet issues page where this had been raised a few times but the issues remain unresolved and still open. There was a response suggesting to downgrade to ipyleaflet 13.0, which did resolve the issues. But it does then mean you cannot import rasters with Leafmap using this version, so it is not a solution for anyone wanting to use Leafmap for rasters with this version. As there are already open issues for this I have not raised a further issue for the same problem.

I have a query which I assume is going to be an ipyleaflet issue too, but it would be great for your confirmation is:
From the toolbox I select create vector data. I load in an esri point shapefile which includes already some column names, which when imported should form the keys in the attribute table in Leafmap automatically. 

If I use a shapefile with no existing points, but containing the defined header names, when I add the shapefile and then the first point, the attribute table has no preset keys - the column names do not appear. 

If I already had a point in the shapefile, for example one added prior to importing to Leafmap in a GIS software, then when I add a new point in Leafmap, it then registers the existing header names and fills in the keys automaically. 

Is there a reason why without an existing point in the shapefile , the Leafmap table cannot register the column headers / keys? Is this to do with the ipyleaflet backend? If it is not possible for columns to show as keys without having a point already in the shapefile, is it possible to increase the number of rows or keys to greater than the 11 maximum?

**Comment by giswqs** [comment]
Are you referring to tutorial 46 https://leafmap.org/notebooks/46_edit_vector/?

**Comment by PennyJClarke** [comment]
@giswqs if I try tutorial 46, the code runs but no shapefile appears in the map window, I am using a shapefile stored in a local directory rather than url.

Instead, I am using your guidance here: https://www.youtube.com/watch?v=RGnXuR60zyk to create vector data without code using the toolbox icon in the map. When the attribute table opens I select the folder icon called open vector data and load the shapefile. As mentioned above, if the shapefile contains an existing point the attribute table Leafmep recognises the column headers and sets them as keys, if the shapefile does not contain an existing point the column headers are not recognised?

**Comment by PennyJClarke** [comment]
Update: I trialed tutorial 46 again to bring in and edit a vector, and it does load the shapefile from a local directory, however, I have the same issues when using the non-coded import method. Where adding a shapefile containing an existing point means Leafmap recognises the column headers and sets them as keys, if the shapefile does not contain an existing point the column headers are not recognised and I would have to define keys? Is there a way to get resolve or get around this? If not is there a method to increase the number of rows in the attribute table to greater than 11? Thank you @giswqs for your time.
