### ISSUE TITLE
Velocity Layer Time Slider

### ISSUE THREAD

**Issue by DrakonianMight** [giswqs/leafmap#344]
### Description

I am not sure if this is an issue or a new feature, so I opted to put this as a new feature, as I cannot see it.
What I am attempting to do as add wind velocity layers to the time slider. It appears that the time slider works, but the layer in the map does not seem to change.
Does this work? If not could this be added?

### Source code

```
import leafmap
import os
import xarray as xr
from ipyleaflet import Map, TileLayer, basemaps, LayerGroup
from ipyleaflet.velocity import Velocity

m = leafmap.Map(layers_control=True,centre = [-25.145, 134.849],zoom = 4)

xr_list = ['list of xarray datasets']

m.add_basemap('CartoDB.DarkMatter')
layers_dict={}
for l in xr_list:
    print(l.time[0].values.astype(str))
    feature_id = l.time[0].values.astype(str)
    wind = Velocity(
        data=l.isel(time = 0),
        zonal_speed="u10",
        meridional_speed="v10",
        latitude_dimension="lat",
        longitude_dimension="lon",
        velocity_scale=0.011,
        max_velocity=30)
    layers_dict[feature_id] = wind
m.add_time_slider(layers_dict, time_interval=1)
m
```

**Comment by giswqs** [comment]
Currently, the time slider only support XYZ tile layers  which have the `url` attribute. Velocity layer does not have the `url` attribute. Instead, it has the `data` attribute. I am not sure if it supports updating the `data` attribute. I might not have time to look into this until next week. PR is welcome.  

https://leafmap.org/toolbar/#leafmap.toolbar.time_slider
https://ipyleaflet.readthedocs.io/en/latest/layers/velocity.html
![image](https://user-images.githubusercontent.com/5016453/213616904-0a15b194-ddc4-4153-aaf7-52a7d33f58d5.png)
