### ISSUE TITLE
Leaf maps options question 

### ISSUE THREAD

**Issue by ziskind60** [giswqs/leafmap#355]
Does leaf maps offer?

1. Direction API to draw path From source to destination.
2. Direction API to calculate the distance from the source to the destination.
3. Show multiple pin locations on the maps.

@⁨Pop⁩ these are the points that need to clear from the Leafmaps support team.

**Comment by giswqs** [comment]
You are welcome to explore WhiteboxTools, which has some distance tools that might be of interest. 

- https://leafmap.org/notebooks/08_whitebox/
- https://www.whiteboxgeo.com/manual/wbt_book/available_tools/gis_analysis_distance_tools.html
