### ISSUE TITLE
cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by benerain** [giswqs/leafmap#358]
### Environment Information

-   leafmap version: 0.16.0
-   Python version: 3.9
-   Operating System: macos

### What I Did
i first create a new conda env and mamba install geospatial package, the installed leafmap version is 0.15.0. 
i update leafmap  to 0.16.0 (conda install leafmap=0.16.0)  and run the stac search notebook example, get the error: 
cannot unpack non-iterable NoneType object 
<img width="1087" alt="截屏2023-02-06 下午4 36 41" src="https://user-images.githubusercontent.com/21291632/216923790-8f7dd277-e13c-42f4-9124-8f2d2a330489.png">
there is one line above said “open() takes from 2 to 4 positional arguments but 6 were given”

could you please tell me how to solve it?

**Comment by giswqs** [comment]
It is likely your installation problem. Try out Colab. 
```bash
!pip install geopandas leafmap
```
https://githubtocolab.com/giswqs/leafmap/blob/master/examples/notebooks/64_stac_search.ipynb
