### ISSUE TITLE
Publication quality maps

### ISSUE THREAD

**Issue by Geethen** [giswqs/leafmap#36]
### Description

Create publication-quality maps with a scale bar, north arrow, and gridlines similar to geemap. Perhaps later, an inset map. variable distribution on the axes edges

### Source code

```
Paste your source code here if have sample code to share.
```

**Comment by giswqs** [comment]
Yes, this would be a nice feature to add, but not on my priority list at the moment. I can't promise when this will get implemented. Pull request is welcome. 

References:

- https://stackoverflow.com/questions/49155110/why-do-my-google-tiles-look-poor-in-a-cartopy-map
- https://scitools.org.uk/cartopy/docs/v0.16/_modules/cartopy/io/img_tiles.html
- https://scitools.org.uk/cartopy/docs/v0.15/examples/eyja_volcano.html
