### ISSUE TITLE
Setting color palette for the add_raster function no long works

### ISSUE THREAD

**Issue by wdkang** [giswqs/leafmap#363]
### Environment Information

-   leafmap version: 0.16.1
-   Python version: 3.10.6
-   Operating System: Planetary Computer Hub

### Description

Trying to to load a single-band local raster on leafmap following the code example from https://leafmap.org/notebooks/05_load_raster/#install-from-conda-forge . Using the 'colormap' parameter does not effectively change the color map (loads the image in the default gray colorway), while using the 'palette' parameter results in an error message (Screenshot attached below).

### What I Did
Using the example code to load a local raster file: Map.add_raster(dem, colormap='terrain', layer_name='DEM')
Could you let me know how to fix the issue and load the raster file with a proper color map?

**Comment by wdkang** [comment]
![error](https://user-images.githubusercontent.com/30909094/217665788-b5a43e65-69ea-4f84-a8a2-37da8a708979.png)

**Comment by giswqs** [comment]
Try updating matplotlib

pip install -U matplotlib

**Comment by wdkang** [comment]
This totally solved the problem. Thanks for your help and prompt reply!
