### ISSUE TITLE
[JupyterLite] Exception: No module named 'ipykernel.ipkernel'

### ISSUE THREAD

**Issue by jtpio** [giswqs/leafmap#402]
### Environment Information

This was noticed while testing `leafmap` on the JupyterLite deployment on https://demo.leafmap.org/lab/index.html.

### Description

Trying to import `leafmap` on a JupyterLite deployment gives the following error:

```
Exception: No module named 'ipykernel.ipkernel'
```

![image](https://user-images.githubusercontent.com/591645/227769737-80668da5-0089-4346-a7c7-5b62b9424d49.png)

This is likely related to the change in https://github.com/giswqs/leafmap/pull/396.

### What I Did

Visit the demo JupyterLite deployment on https://demo.leafmap.org.

**Comment by giswqs** [comment]
@jtpio Thanks for reporting. It seems the ipykernel bug has been fixed upstream by ipywidgets. I will remove the ipykernel import from leafmap.

**Comment by stevecwlau** [comment]
> @jtpio Thanks for reporting. It seems the ipykernel bug has been fixed upstream by ipywidgets. I will remove the ipykernel import from leafmap.

Hi Dr. Wu. I am also facing some issues with ipykernel in JupyterLite. Here's what I did:
![Untitled](https://github.com/opengeos/leafmap/assets/91710999/2b1b8e33-86e1-4bef-8485-03888b5bc39c)

**Comment by giswqs** [comment]
This appears to be an ipywidgets/ipykernel issue with JupyterLite. There is not much leafmap can do. I have not use JupyterLite for a while. 

I would suggest using Colab or install JupyterLab locally.

**Comment by jtpio** [comment]
@stevecwlau this was indeed an issue reported in https://github.com/jupyter-widgets/ipywidgets/issues/3819.

But should now be fixed with the latest version of `jupyterlite-pyodide-kernel`. So updating the version and / or triggering a new build of the JupyterLite website should fix it.
