### ISSUE TITLE
Upon installation, environment variables can be used to configure what widgets are available in the toolbar

### ISSUE THREAD

**Issue by abarciauskas-bgse** [giswqs/leafmap#405]
### Description

There are a lot of widgets available in the tool bar, it would be preferable if upon installation of leafmap, the person installing the library could configure which widgets will show up in the default map. For example, I may just want the STAC widget and nothing else.

**Comment by giswqs** [comment]
Let me know the name of the environment variable you would like to use.

**Comment by abarciauskas-bgse** [comment]
🤔 I would think that each widget would have an environment variable, with a default value of "TRUE" or "FALSE", for example:
```
export WHITEBOX=FALSE
export TS_INSPECTOR=FALSE
export CREATE_VECTOR=FALSE
...
pip install leafmap
```

and then when the user creates a map with 

```
import leafmap
m = leafmap.Map()
m
```

and you click the wrench 🔧 icon you only see the widget options set to "TRUE"

for MAAP's initial use case, we may only use "Discover STAC Catalog" widgeth.
