### ISSUE TITLE
Add wms value for the active layer on click event (info button) 

### ISSUE THREAD

**Issue by rcumani** [giswqs/leafmap#54]
### Description

Describe the feature (e.g., new functions/tutorials) you would like to propose.
Tell us what can be achieved with this new feature and what's the expected outcome.

It is possible to add WMS layer and to manage rendering through the legend templates. It will be good to add an event / button that shows the pixel lat, lon and value. 

### Source code

```
Paste your source code here if have sample code to share.
```

**Comment by giswqs** [comment]
Unfortunately, folium/ipyleaflet does not support WMS getInfo. This has to be implemented in the JavaScript backend. You are welcome to make a feature request on the [ipyleaflet repo](https://github.com/jupyter-widgets/ipyleaflet/issues). Leafmap won't support this unless ipyleaflet supports it.   

Reference: https://astuntechnology.github.io/osgis-ol3-leaflet/leaflet/05-WMS-INFO.html
