### ISSUE TITLE
color map

### ISSUE THREAD

**Issue by shi093** [giswqs/leafmap#78]
How to color a polygon layer based on a variable value? like the thermal map. The polygons can be colored by specifying fillColor in Style, like the example in your tutorial:
style = {
    "stroke": True,
    "color": "#FFFFFF",
    "weight": 1,
    "opacity": 0.7,
    "fill": True,
    "fillColor": "blue",
    "fillOpacity": 0.4,
}
Is there a way to make "fillColor" a function of a data field from geopandas dataframe the map plots? 

Thank you very much.

**Comment by giswqs** [comment]
See https://github.com/giswqs/leafmap/issues/28#issuecomment-859761849
