### ISSUE TITLE
Render ipyleaflet and ipywidgets in mkdocs-jupyter

### ISSUE THREAD

**Issue by giswqs** [giswqs/leafmap#85]
The documentation website (https://leafmap.org) is built using [MkDocs](https://squidfunk.github.io/mkdocs-material/) and [mkdocs-jupyter](https://github.com/danielfrg/mkdocs-jupyter) with GitHub Actions ([mkdocs.yml](https://github.com/giswqs/leafmap/blob/master/mkdocs.yml) and [docs.yml](https://github.com/giswqs/leafmap/blob/master/.github/workflows/docs.yml)). Currently, it seems mkdocs-jupyter can only render folium maps. Ipyleaflet maps and ipywidgets do not show up on the webpage. Any advice on making the ipyleaflet-based interactive maps show up on https://leafmap.org would be greatly appreciated. 

Examples:

- folium: https://leafmap.org/notebooks/01_leafmap_intro (interactive map working)
- ipyleaflet: https://leafmap.org/notebooks/18_point_layer (interactive map does not show up)
- heremap: https://leafmap.org/notebooks/16_heremap (interactive map does not show up)

@deeplook @sackh @martinRenou @davidbrochart @danielfrg @squidfunk @chrieke

**Comment by danielfrg** [comment]
I think the main issue is that the mkdocs-jupyter does not include the `amd-embed.js` from jupyter-widgets. 

Take a look at: https://ipywidgets.readthedocs.io/en/latest/embedding.html

Maybe just including the JS into the mkdocs-material template will do it.

**Comment by giswqs** [comment]
@danielfrg Thank you for the advice. Can it (`including the JS into the mkdocs-material template`) be done within this repo or it has to be fixed by mkdocs-material?

**Comment by danielfrg** [comment]
It can be done in this repo: https://squidfunk.github.io/mkdocs-material/customization/

**Comment by giswqs** [comment]
I following the [MkDocs customization instruction](https://squidfunk.github.io/mkdocs-material/customization/#additional-javascript) to add two JavaScripts to the `docs` directory and add the following lines to `mkdocs.yml`.  However, ipyleaflet maps still do not show up. Should I also modify [main.html](https://github.com/giswqs/leafmap/blob/master/docs/overrides/main.html) and how? Sorry, my JavaScript knowledge is very limited. Any help will be appreciated. 

```
extra_javascript:
    - javascripts/embed-amd.js
    - javascripts/require.min.js
```

**Comment by giswqs** [comment]
This is what it looks like when I clicked on the [`Embed widgets` menu](https://ipywidgets.readthedocs.io/en/latest/embedding.html).

![image](https://user-images.githubusercontent.com/5016453/125686369-9f43c306-0974-467f-9e78-69ace6014b6b.png)
