### ISSUE TITLE
ipyevents@2.0.1 cannot be found on CDN (unpkg.com)

### ISSUE THREAD

**Issue by helincao** [giswqs/leafmap#87]
### Environment Information

-   leafmap version: 0.3.3
-   Python version: 3.8
-   Operating System: Linux

### Description
Leafmap 0.3.3 uses ipyevents@2.0.1. However, the new ipyevent cannot be found on CDN: 
Error message from Chrome console:
![image](https://user-images.githubusercontent.com/18755763/126267022-543707e4-a0ba-4bd4-8262-87444a1ea03e.png)

Response from CDN:
![image](https://user-images.githubusercontent.com/18755763/126266378-c2984eab-f909-41ea-b35e-7ab3b247be17.png)

**Comment by giswqs** [comment]
Thanks for reporting. Would downgrading ipyevents to v2.0.0 resolve the issue? If yes, then this is bug that needs to be reported on the ipyevents repo. We can temporarily pin ipyevents v2.0.0 in the requirements.txt

**Comment by helincao** [comment]
As far as I can see, v1.9.0's cdn works: https://unpkg.com/ipyevents@1.9.0/dist/index.js

However, v2.0.0 does not: https://unpkg.com/ipyevents@2.0.0/dist/index.js

Let me report the issue to ipyevents.

**Comment by giswqs** [comment]
ipyevents v2.0.0 and v2.0.1 were just released a few days ago. From the release history, I can't find v1.9.0. Only see v0.9.0

https://github.com/mwcraig/ipyevents/releases
https://pypi.org/project/ipyevents/#history

**Comment by helincao** [comment]
v0.9.0 should work. This version points to `ipyevents@1.9.0/dist/index.js`

Their version naming is confusing though... 
![image](https://user-images.githubusercontent.com/18755763/126359081-a1387d84-cc34-499c-9d16-7d785bdf6802.png)

Anyway, an issue is opened on that project: https://github.com/mwcraig/ipyevents/issues/70

**Comment by giswqs** [comment]
I have added ipyevents v0.9.0 to requirements.txt. Will make a new release later this week. We can remove the version restriction once the issue is fixed by ipyevents. 
https://github.com/giswqs/leafmap/blob/master/requirements.txt#L6

**Comment by giswqs** [comment]
Leafmap v0.3.4 has been released. The pip version uses ipyevents <= 0.9.0. Note that the conda-forge version does not specify ipyevents version.

**Comment by helincao** [comment]
Thanks for the change. The author of ipyevents confirmed to support npm for newer versions.
